version: '2'
services:
    graphql-app:
        image: graphql
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://graphql-mysql:3306/graphql?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    graphql-mysql:
        extends:
            file: mysql.yml
            service: graphql-mysql
